travis:
  secure:
    BINSTAR_TOKEN: yl52cUbnh/tAvUyuOzKkjmznE7bHDDHA2pgmwwQ3UtoIRUTyJ0pODUbC9L5nmrI/ugZmCeCS4e14+mbgV7cSbTXA+w/ru4Sulu5YDNDpmhvqspo3kPUZxEcVoe85h/am3i+boo2VE4u9xbk6x+h45bj9I3ZwhGF2SuB0Yh3OFmlRWrD+EHz08aRx+sKRiwulEw7fztv/kWZM54TmIVfDg/Gysz/+JdouCcw+dDC2UvIXt/jnS8zTPB3CIxoy6np59pwp5LEP9kert54ZNXj/eu2ostxke+OiMldD5axlZR1QqOzZkqaaFP/e9wP5XvOlUpISI1VPUgHI+s/0vzg2v8ydpi/P5zVRRKaRSYcJU2nxNXoi6nW5BvvalkI9VUXCzw8N9QNTpf96XfZqZtefndIgP0+KvReXlWNMKjIsGciwIPW0IXIN/DceOGYykeAKcceXQedS+NYcHhNPaqOYpx25EszrxzfWQW6KONFCn+VVp3C0YgeiYNKhJeiZaQDmY8rvUE3iE2gnD4vE1k0UdxsXGEI1tX69S/el+woBYiLcr1rsyi8rnUlpfDz+gwn/FKwgRhnd22+lE6pnCX4xH/yiv74aBxVBKi11ITGnGJUWaSwL+9swVjBuvtCC7I3GrQ39h+b+p49hg7pFnEUUhdHDyijQFhjzPt7z2BivLsM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
